### ISSUE TITLE
DRY out Makefile

### ISSUE THREAD

**Issue by mstefferson** [manifoldai/orbyter-docker#69]
Figure out how to DRY out the repeated commands in the Makefile

**Comment by mstefferson** [comment]
https://stackoverflow.com/questions/2826029/passing-additional-variables-from-command-line-to-make

**Comment by gg314** [comment]
Made a [commit](https://github.com/manifoldai/orbyter-docker/pull/124/commits/f03790b00e5462baf59e1cdb8622d1e0411a7efc) to achieve this but I'm not convinced I like it.

* GNU Make sucks and it will be easy for someone to struggle/waste time editing this in the future
* Auto-complete works due to folder name, not due to `make` targets:
  * Old: `make build-base-sys`
  * New: `make build target=orbyter-base-sys`

I think I'll leave it in the PR unless someone complains.
